name: homecredit
channels: [conda-forge]
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.5
  - lightgbm=4.5
  - catboost=1.2
  - xgboost=2.1
  - matplotlib=3.9
  - seaborn=0.13
  - pyyaml=6.0
  - optuna=3.6
  - jupyterlab=4.2
  - pip
  - pip:
      - kaggle==1.6.14
      - mlflow==2.16
      - pre-commit==3.8
      - nbstripout==0.6.1
